name: Build Java app

on:
  push: 
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]  

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
